### ISSUE TITLE
Update Splinetools to latest version 

### ISSUE THREAD

**Issue by naj147** [hongkiulam/threlte-spline#12]
Your dependency on spline-tool libs is capped in the following code : "@splinetool/loader": ">=0.9 <1"
Using this helper leads to an issue where the splines don't load with the code error asking to update the tools to a version that supports this .splinecode

I see you haven't updated the repo for a while, I could help with the updates if there is need to.

Thank you for the fantastic helper and hope it stays active ❤️

**Comment by hongkiulam** [comment]
Hey, thanks for bringing this up!

I can look into this but please do send over a PR to review if you're happy to do so :)

**Comment by hongkiulam** [comment]
I have something readyish, just gotta cleanup, should be published in the next few days
