### ISSUE TITLE
dist missing in 0.5.0

### ISSUE THREAD

**Issue by ermincelikovic** [hongkiulam/threlte-spline#14]
Hi there,

I wanted to use the the package, but it seems like dist is missing in the latest version :)

**Comment by hongkiulam** [comment]
Thanks for reporting, that has now been fixed in 0.5.1, turns out I wasn't running `pnpm build` after updating some package.json scripts

**Comment by ermincelikovic** [comment]
No worries. Thanks for the quick fix!
Btw. Is the package compatible with threlte 7?

**Comment by hongkiulam** [comment]
wow threlte 7 already! It should be compatible. This package will simply expose Three.js props, so from what I can see you can still do the following
```html

<T.Mesh position={scene.nodes['Box'].position} />
```

**Comment by ermincelikovic** [comment]
Yeah, they are already having 8.0@next getting ready, probably to release it with Svelte 5.

Cool, will check it out. Thanks for the library!
